import type { Metadata } from "next";
import "./globals.css";
import { Poppins } from "next/font/google";

const pospins = Poppins({
  subsets: ["latin"],
  weight: ['100', '200', '300', '400', '500', '600', '700', '800', '900'],
  variable: '--font-poppins',
})

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${pospins.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
